version: "3.9"
services:
    django:
        build: ./edagames-django
        ports:
            - "8000:8000"
        volumes: 
            - ${PWD}/edagames-django/db.sqlite3:/edagames-django/db.sqlite3
        environment:
            - SECRET_KEY
            - SECRET_KEY_JWT
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET
            - SERVER_URL=http://server
            - SERVER_PORT=5000
        depends_on: 
            - server
            - django-db
    quoridor:
        build: ./edagames-quoridor
        environment:
            - QUORIDOR_GRPC_PORT=50051
        depends_on:
            - redis
    server:
        build: ./edagames-server
        ports:
            - "5000:5000"
        environment:
            - TOKEN_KEY=${SECRET_KEY_JWT}
            - WEB_SERVER_URL=django
            - WEB_SERVER_PORT=8000
            - QUORIDOR_HOST_PORT=quoridor:50051
            - REDIS_HOST=redis
        depends_on:
            - redis
            - quoridor
    redis:
        image: redis:6.2-alpine
    django-db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=edagames
            - MYSQL_PASSWORD=asd
            - MYSQL_DATABASE=edagames-web
            - MYSQL_RANDOM_ROOT_PASSWORD=1
