version: "3.9"
services:
    django:
        build: ./edagames-django
        ports:
            - "8000:8000"
        volumes:
            - ${PWD}/edagames-django/:/edagames-django/
        environment:
            - SECRET_KEY
            - SECRET_KEY_JWT
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET
            - SERVER_URL=http://server
            - SERVER_PORT=5000
            - DJANGO_DB_HOST=django-db
            - DJANGO_DB_PORT=3306
            - DJANGO_DB_NAME
            - DJANGO_DB_USER
            - DJANGO_DB_PASSWORD
        depends_on:
            - server
            - django-db
        stdin_open: true # debug pdb
        tty: true # debug pdb
        entrypoint: python manage.py runserver 0.0.0.0:8000 --settings=edagames.settings.local
    quoridor:
        build: ./edagames-quoridor
        volumes:
            - ${PWD}/edagames-quoridor/:/edagames-quoridor/
        environment:
            - QUORIDOR_GRPC_PORT=50051
            - REDIS_DB_INDEX=1
            - REDIS_HOST=redis
        depends_on:
            - redis
        stdin_open: true # debug pdb
        tty: true # debug pdb
    wumpus:
        build: ./edagames-wumpus
        volumes:
            - ${PWD}/edagames-wumpus/:/edagames-wumpus/
        environment:
            - WUMPUS_GRPC_PORT=50052
            - REDIS_DB_INDEX=1
            - REDIS_HOST=redis
        depends_on:
            - redis
        stdin_open: true # debug pdb
        tty: true # debug pdb
    server:
        build: ./edagames-server
        ports:
            - "5000:5000"
        volumes:
            - ${PWD}/edagames-server/:/app/
        environment:
            - TOKEN_KEY=${SECRET_KEY_JWT}
            - WEB_SERVER_URL=django
            - WEB_SERVER_PORT=8000
            - QUORIDOR_HOST_PORT=quoridor:50051
            - WUMPUS_HOST_PORT=wumpus:50052
            - REDIS_HOST=redis
            # - RABBIT_HOST=rabbit
        depends_on:
            - redis
            - quoridor
            - wumpus
            # - rabbit
        stdin_open: true # debug pdb
        tty: true # debug pdb
        restart: unless-stopped
    redis:
        image: redis:6.2-alpine
    # rabbit:
    #     image: rabbitmq:3.8-alpine
    django-db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DJANGO_DB_NAME}
            - MYSQL_USER=${DJANGO_DB_USER}
            - MYSQL_PASSWORD=${DJANGO_DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=1
