version: "3.9"
services:
    django:
        build: ./edagames-django
        ports:
            - "8000:8000"
        volumes: 
            - ${PWD}/edagames-django/db.sqlite3:/edagames-django/db.sqlite3
        environment:
            - SECRET_KEY
            - SECRET_KEY_JWT
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET
            - SERVER_URL=http://server
            - SERVER_PORT=5000
        depends_on: 
            - server
    quoridor:
        build: ./edagames-quoridor
    server:
        build: ./edagames-server
        ports:
            - "5000:5000"
        environment:
            - TOKEN_KEY=${SECRET_KEY_JWT}
            - WEB_SERVER_URL=django
            - WEB_SERVER_PORT=8000
            - QUORIDOR_HOST_PORT=quoridor:50051
            - REDIS_HOST=redis
    redis:
        image: redis:6.2-alpine
