version: 2.1

jobs:
  flake8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies-dev
          command: pip install -r requirements-dev.txt
      - run:
          name: Run Flake8 checks
          command: flake8
  integration-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Start docker compose
          command: docker compose up -d
      - run:
          name: Load test dataset
          command: mysql -u edagames -p ${WEB_MYSQL_PASSWORD} < integration_tests/test_data.sql
      - run:
          name: Start integration test
          command: cd integration_tests && python test.py

workflows:
  push:
    jobs:
      - flake8
  integration:
    triggers:
      - schedule:
          cron: "0 12,17 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - integration-tests
