version: 2.1

jobs:
  flake8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies-dev
          command: pip install -r requirements-dev.txt
      - run:
          name: Run Flake8 checks
          command: flake8
  integration-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Start docker compose
          command: docker compose -f docker-compose.yml -f compose-integration.yml up -d
      - run:
          name: Load test dataset
          command: cat integration_tests/test_data.sql | docker compose exec -i django-db /usr/bin/mysql -u ${DJANGO_DB_USER} --password=${DJANGO_DB_PASSWORD} ${DJANGO_DB_NAME}
      - run:
          name: Start integration test
          command: cd integration_tests && python test.py

workflows:
  push:
    jobs:
      - flake8
  integration:
    triggers:
      - schedule:
          cron: "0 12,17 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - integration-tests
