apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: edagames
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: public.ecr.aws/v1m7n2g6/edagames-server
          name: server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-k8s-master
            - name: QUORIDOR_HOST_PORT
              value: quoridor:50051
            - name: TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: edagames-secrets
                  key: TOKEN_KEY
            - name: WEB_SERVER_URL
              value: django
            - name: WEB_SERVER_PORT
              value: "8000"
            - name: SERVER_CLIENT_CONNECTION_TYPE
              value: "api_gateway"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: edagames-server-ws-api
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: edagames-server-ws-api
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: edagames-server-ws-api
                  key: AWS_DEFAULT_REGION
