apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: edagames
spec:
  ports:
    - name: server-port
      port: 5000
      targetPort: 5000
  selector:
    app: server
---
apiVersion: v1
kind: Service
metadata:
  name: server-lb
  namespace: edagames
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
