apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: edagames
spec:
  ports:
    - name: server-port
      port: 5000
      targetPort: 5000
  selector:
    app: server
