apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quoridor
  name: quoridor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoridor
  template:
    metadata:
      labels:
        app: quoridor
    spec:
      containers:
        - image: quoridor
          name: quoridor
      restartPolicy: Always