apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::402784727777:role/aws_load_balancer_role
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eks
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
      version: '1.4.1'
  interval: 10m0s
  targetNamespace: kube-system
  values:
    clusterName: edagames-cluster
    serviceAccount:
      create: false
      name: aws-load-balancer
    region: us-east-1
