apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ack
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::402784727777:role/aws_ack_role
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ack-apigatewayv2
  namespace: flux-system
spec:
  interval: 10m0s
  type: OCI
  url: oci://public.ecr.aws/aws-controllers-k8s/apigatewayv2-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ack-apigateway
  namespace: flux-system
spec:
  releaseName: ack-apigatewayv2-controller
  chart:
    spec:
      chart: ack-apigatewayv2-controller
      sourceRef:
        kind: HelmRepository
        name: ack-apigatewayv2
      version: '0.1.0'
  interval: 10m0s
  targetNamespace: kube-system
  values:
    serviceAccount:
      create: false
      name: aws-ack
    aws:
      region: us-east-1
