apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: edagames
data:
  values.yaml: |
    auth:
      database: edagames_web
      username: django
      existingSecret: edagames-secrets
    secondary:
      replicaCount: 0
