---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: flux-system
spec:
  releaseName: mysql-k8s
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '8.8.26'
  interval: 10m0s
  targetNamespace: edagames
  valuesFrom:
  - kind: ConfigMap
    name: mysql-config
