---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  releaseName: redis-k8s
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '16.5.2'
  interval: 10m0s
  targetNamespace: edagames
  valuesFrom:
  - kind: ConfigMap
    name: redis-config
