apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
  name: django
  namespace: edagames
spec:
  ports:
    - name: django-port
      port: 8000
      targetPort: 8000
  selector:
    app: django
