apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
  name: django
  namespace: edagames
spec:
  ports:
    - name: django-port
      port: 8000
      targetPort: 8000
  selector:
    app: django
---
apiVersion: v1
kind: Service
metadata:
  name: django-lb
  namespace: edagames
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
