# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ack-apigatewayv2-controller
#   namespace: kube-system
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::402784727777:role/aws_ack_role
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ack-apigateway
  namespace: flux-system
spec:
  releaseName: ack-apigatewayv2-controller
  chart:
    spec:
      # chart: ack-apigatewayv2-controller
      # sourceRef:
      #   kind: HelmRepository
      #   name: ack-apigatewayv2
      chart: ./kubernetes/edagames/infrastructure/apigatewayv2-chart-v0.1.0.tgz
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: '0.1.0'
  interval: 10m0s
  targetNamespace: kube-system
  values:
    serviceAccount:
      create: true
      name: ack-apigatewayv2-controller
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::402784727777:role/aws_ack_role
    aws:
      region: us-east-1
