apiVersion: v1
kind: Service
metadata:
  labels:
    app: quoridor
  name: quoridor
  namespace: edagames
spec:
  ports:
    - name: quoridor-port
      port: 50051
      targetPort: 50051
  selector:
    app: quoridor
