apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: edagames-quoridor
  namespace: flux-system
spec:
  dependsOn:
    - name: edagames-services
  interval: 10m0s
  path: ./edagames/quoridor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
