apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: edagames-services
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./services
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
