apiVersion: v1
kind: Service
metadata:
  labels:
    app: wumpus
  name: wumpus
  namespace: edagames
spec:
  ports:
    - name: wumpus-port
      port: 50052
      targetPort: 50052
  selector:
    app: wumpus
