apiVersion: v1
kind: Service
metadata:
  labels:
    app: react
  name: react
  namespace: edagames
spec:
  ports:
    - name: react-port
      port: 3000
      targetPort: 3000
  selector:
    app: react
---
apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: edagames
spec:
  type: ClusterIP
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
